// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyrlonH6AYSWTBx99a2abcb7YzuvCJmkY',
    appId: '1:246932402347:web:e457e3a9c0db09ce2dc7ee',
    messagingSenderId: '246932402347',
    projectId: 'kh-mynotes-flutter',
    authDomain: 'kh-mynotes-flutter.firebaseapp.com',
    storageBucket: 'kh-mynotes-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdhZowfNafbj3ZU8uLi0WfO5xyuh6ue_Y',
    appId: '1:246932402347:android:b90be376a3cd179e2dc7ee',
    messagingSenderId: '246932402347',
    projectId: 'kh-mynotes-flutter',
    storageBucket: 'kh-mynotes-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuI4BVtULZ3rLL8cWmviCyJgElKZ4tXX0',
    appId: '1:246932402347:ios:384cfc633b69085e2dc7ee',
    messagingSenderId: '246932402347',
    projectId: 'kh-mynotes-flutter',
    storageBucket: 'kh-mynotes-flutter.appspot.com',
    iosClientId: '246932402347-80ue3s3c21lpthpuij930p8val9bmefo.apps.googleusercontent.com',
    iosBundleId: 'com.khaled.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuI4BVtULZ3rLL8cWmviCyJgElKZ4tXX0',
    appId: '1:246932402347:ios:384cfc633b69085e2dc7ee',
    messagingSenderId: '246932402347',
    projectId: 'kh-mynotes-flutter',
    storageBucket: 'kh-mynotes-flutter.appspot.com',
    iosClientId: '246932402347-80ue3s3c21lpthpuij930p8val9bmefo.apps.googleusercontent.com',
    iosBundleId: 'com.khaled.mynotes',
  );
}
