class DatabaseAlreadyOpenException implements Exception {}
class DatabaseIsNotOpenException implements Exception {}
class UnableToGetDocumentDirectoryException implements Exception {}
class CouldNotDeleteUser implements Exception {}
class CouldNotFindUser implements Exception {}
class CouldNotDeleteNote implements Exception {}
class CouldNotFindNote implements Exception {}
class CouldNotUpdateNote implements Exception {}
class UserAlreadyExistsException implements Exception {}
